### ISSUE TITLE
Video is playing very fast with the python script

### ISSUE THREAD

**Issue by testaccountsnt** [aadil494/CommandLineAsciiVideoPlayer#2]
Hi,
I am running the python script and it has opened the video frame window and running the ASCII video in the terminal successfully but the video play speed is very fast. I can hardly see anything.
Video file duration is 27 seconds and it is played fine in the video player but it is done with in 10 seconds with the python script.
How should I control the video play speed, should I pass any parameter with the python script filename?
My Python version 3.8.2
pip version : 21.2.4
All packages are installed which are mentioned in the requirements.txt

Thank You

**Comment by aadil494** [comment]
you can always play with the values of cv2.waitKey() function, in the script it is set to 1 you can change it to 10 , 20 ,50 ,100 as per your need , so your waitKey should look like this cv2.waitKey(50) or cv2.waitKey(100) or whatever value that will give you the desired results

**Comment by testaccountsnt** [comment]
It worked. Thank You.
